FROM python:3.11-slim
WORKDIR /app
COPY demo_target/requirements.txt /tmp/req.txt 
COPY demo_target /app
RUN pip install fastapi uvicorn
EXPOSE 8001
CMD ["uvicorn","app:app","--host","0.0.0.0","--port","8001"]
